### PR TITLE
text: fix jsonify bug

### PR DESCRIPTION
**Pull request by jacenkow**
- Updates text endpoint to return a dictionary instead of a string.

Signed-off-by: Grzegorz Jacenków grzegorz.jacenkow@cern.ch

### CODE REVIEW

**Comment by jacenkow** [comment]
Resolves #8.

**Comment by jacenkow** [comment]
CC: @kaplun

**Comment by kaplun** [comment]
Wanted to say that you could merge it :)
P.s. next time put `Closes #8` directly in the commit log, so that it closes automatically and we track tickets.

**Comment by jacenkow** [comment]
@kaplun sorry 👍

**Pull request merged**
